/* This file is auto generated by C-Sugar @author Steven Dellamore */

// author: Steven Dellamore
// date: 2020-2-17
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>


using namespace std;

int main()
{
    int N;
    cin >> N; cin.ignore();
    // vec @TODO
    auto vec = std::vector< int >();
    for (int i = 0; i < N; i++) {
        string PATH;
        getline(cin, PATH);
        // n @TODO
        auto n = count(PATH.begin(), PATH.end(), '/');
        vec.push_back( n ); // pushing  n  onto vec

    }

    // Printing out the entire vec vector with delim: "\n"
    for (auto i = vec.begin(); i != vec.end(); ++i)
    {
        std::cout << *i << "\n";
    }
}