/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-20
// version: 1.0.0

#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>

#include <math.h>

int main()
{
    std::string N;
    std::getline(std::cin, N);
    // num @TODO
    int num = 0;
    int j = 0;
    std::for_each( N.begin(), N.end(), 
        [&j, &num](auto c){
            // print("std::atoi: " + std::atoi(&c) + "\n");
            num += (std::atoi(&c) * pow(-2, j));
            // print("Num: " + num + "\n");
            j++;
        } 
    );

    std::cout << num;
}