/* This file is auto generated by C-Sugar @author Steven Dellamore */

// author: Steven Dellamore
// date: 2020-2-17
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>

using namespace std;

int main()
{
    string B;
    cin >> B; cin.ignore();

    string newTok = "";

    for_each(B.begin(), B.end(), [&newTok](auto c){
        if(c == '0'){
            newTok += "1";
        } else{
            newTok += "0";
        }
    });
    
    std::cout <<  newTok << "\n";
}