/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>

// def int add(int a, int b, int c, std::vector<int> d) {
//     printv(d, ", ");
//     return (a+b+c);
// }

template <typename T, typename U, typename G, typename H >
auto add( T a, U b, G c, H d ) {
    // Printing out the entire d vector with delim: ", "
    for (auto i = d.begin(); i != d.end(); ++i)
    {
        std::cout << *i << ", ";
    }
    return (a+b+c);
}

int main() {
    // vec @TODO
    auto vec = std::vector< int >();
    vec.push_back(1); // pushing 1 onto vec
    vec.push_back(2); // pushing 2 onto vec
    vec.push_back(3); // pushing 3 onto vec
    // x @TODO
    auto x = add(1, 2, 9, vec);
    std::cout << x << "\n";
}