/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-23
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>

using namespace std;

int main()
{
    int N;
    cin >> N; cin.ignore();

    // str @TODO
    auto str = to_string( N );
    if(str.length() == 1) {
        std::cout <<  str  << std::endl;
        return 1;
    }
    str = str.substr( str.length() - 1, str.length() - 1 );
    std::cout <<  str  << std::endl;
    
    /* Does not work with Negatives */
    // var lastDig = N % 10;

    // println( lastDig );
}