/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-26
// version: 1.0.0


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>
#include <bitset>
#include <math.h>
#include <iomanip> 

using namespace std;

int main() {
    int n;
    cin >> n; cin.ignore();
    std::cout << "0";
    for(int i = 0; i < n; i++) {
        std::string str = std::bitset< 64 >( i ).to_string(); 
        std::string str2 = "";
        for(// j @TODO
        int j = 0; j < (int)log2(i)+1; j++){
            str2 += str.at(str.length() - j - 1);
        }
        std::reverse(str2.begin(), str2.end());
        std::cout << str2 << std::endl;
    }
}