/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>

using namespace std;

template <typename T, typename U, typename G, typename H >
int max_of_four( T a, U b, G c, H d ) {
    return int ( std::max( std::max( a ,b ), std::max( c, d ) ) );
}

int main() {
    int a, b, c, d;
    scanf("%d %d %d %d", &a, &b, &c, &d);
    // ans @TODO
    auto ans = max_of_four(a, b, c, d);
    std::cout << ans << std::endl;
    
    return 0;
}