/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>

using namespace std;

int main()
{
    int n;
    cin >> n;
    cin.ignore(numeric_limits<streamsize>::max(), '\n');

    switch(n){
        case 0: 
            std::cout << "zero" << std::endl;
            break;
        case 1: 
            std::cout << "one" << std::endl;
            break;
        case 2: 
            std::cout << "two" << std::endl;
            break;
        case 3: 
            std::cout << "three" << std::endl;
            break;
        case 4: 
            std::cout << "four" << std::endl;
            break;
        case 5: 
            std::cout << "five" << std::endl;
            break;
        case 6: 
            std::cout << "six" << std::endl;
            break;
        case 7:
            std::cout << "seven" << std::endl;
            break;
        case 8: 
            std::cout << "eight" << std::endl;
            break;
        case 9:
            std::cout << "nine" << std::endl;
            break;
        default: 
            std::cout << "Greater than 9" << std::endl;
            break;
    }

    return 0;
}
